import type { DefaultOptionType } from 'antd/es/select';

export const REGION_IDS = {
  afghanistan: 'afghanistan',
  africa: 'africa',
  albania: 'albania',
  algeria: 'algeria',
  americanSamoa: 'americanSamoa',
  andorra: 'andorra',
  angola: 'angola',
  anguilla: 'anguilla',
  antiguaAndBarbuda: 'antiguaAndBarbuda',
  argentina: 'argentina',
  armenia: 'armenia',
  aruba: 'aruba',
  asia: 'asia',
  australia: 'australia',
  australiaOceania: 'australiaOceania',
  austria: 'austria',
  azerbaijan: 'azerbaijan',
  bahamas: 'bahamas',
  bahrain: 'bahrain',
  bangladesh: 'bangladesh',
  barbados: 'barbados',
  belarus: 'belarus',
  belgium: 'belgium',
  belize: 'belize',
  benin: 'benin',
  bermuda: 'bermuda',
  bhutan: 'bhutan',
  bolivia: 'bolivia',
  bosniaHerzegovinaCantons: 'bosniaHerzegovinaCantons',
  bosniaHerzegovinaRegions: 'bosniaHerzegovinaRegions',
  botswana: 'botswana',
  brazil: 'brazil',
  britishVirginIslands: 'britishVirginIslands',
  bruneiDarussalam: 'bruneiDarussalam',
  bulgaria: 'bulgaria',
  burkinaFaso: 'burkinaFaso',
  burundi: 'burundi',
  cambodia: 'cambodia',
  cameroon: 'cameroon',
  canada: 'canada',
  capeVerde: 'capeVerde',
  caribbean: 'caribbean',
  caribbeanNetherlands: 'caribbeanNetherlands',
  caymanIslands: 'caymanIslands',
  centralAfricanRepublic: 'centralAfricanRepublic',
  centralAmerica: 'centralAmerica',
  chad: 'chad',
  channelIslands: 'channelIslands',
  chile: 'chile',
  china: 'china',
  christmasIsland: 'christmasIsland',
  cocosIslands: 'cocosIslands',
  colombia: 'colombia',
  comoros: 'comoros',
  congoDR: 'congoDR',
  congo: 'congo',
  continentsRegions: 'continentsRegions',
  continentsRussiaAntarctica: 'continentsRussiaAntarctica',
  cookIslands: 'cookIslands',
  costaRica: 'costaRica',
  croatia: 'croatia',
  cuba: 'cuba',
  curacao: 'curacao',
  cyprus: 'cyprus',
  cyprusNorthernCyprus: 'cyprusNorthernCyprus',
  czechRepublic: 'czechRepublic',
  denmark: 'denmark',
  djibouti: 'djibouti',
  dominica: 'dominica',
  dominicanRepublic: 'dominicanRepublic',
  eastTimor: 'eastTimor',
  ecuador: 'ecuador',
  egypt: 'egypt',
  elSalvador: 'elSalvador',
  equatorialGuinea: 'equatorialGuinea',
  eritrea: 'eritrea',
  estonia: 'estonia',
  eSwatini: 'eSwatini',
  ethiopia: 'ethiopia',
  europe: 'europe',
  falklandIslands: 'falklandIslands',
  faroeIslands: 'faroeIslands',
  fijiEast: 'fijiEast',
  fijiWest: 'fijiWest',
  finland: 'finland',
  france2016: 'france2016',
  franceDepartments: 'franceDepartments',
  france: 'france',
  frenchGuiana: 'frenchGuiana',
  frenchPolynesia: 'frenchPolynesia',
  gabon: 'gabon',
  gambia: 'gambia',
  georgia: 'georgia',
  georgiaWithSouthOssetia: 'georgiaWithSouthOssetia',
  germany: 'germany',
  ghana: 'ghana',
  gibraltar: 'gibraltar',
  greece: 'greece',
  greenland: 'greenland',
  grenada: 'grenada',
  guadeloupe: 'guadeloupe',
  guam: 'guam',
  guatemala: 'guatemala',
  guineaBissau: 'guineaBissau',
  guinea: 'guinea',
  guyana: 'guyana',
  haiti: 'haiti',
  honduras: 'honduras',
  hongKong: 'hongKong',
  hungary: 'hungary',
  iceland: 'iceland',
  india2019: 'india2019',
  india: 'india',
  indonesia: 'indonesia',
  iran: 'iran',
  iraq: 'iraq',
  ireland: 'ireland',
  isleOfMan: 'isleOfMan',
  israel: 'israel',
  israelPalestine: 'israelPalestine',
  italy: 'italy',
  ivoryCoast: 'ivoryCoast',
  jamaica: 'jamaica',
  japan: 'japan',
  jersey: 'jersey',
  jordan: 'jordan',
  kazakhstan: 'kazakhstan',
  kenya: 'kenya',
  kiribati: 'kiribati',
  kosovo: 'kosovo',
  kuwait: 'kuwait',
  kyrgyzstan: 'kyrgyzstan',
  laos: 'laos',
  latinAmerica: 'latinAmerica',
  latvia: 'latvia',
  lebanon: 'lebanon',
  lesotho: 'lesotho',
  liberia: 'liberia',
  libya: 'libya',
  liechtenstein: 'liechtenstein',
  lithuania: 'lithuania',
  luxembourg: 'luxembourg',
  macao: 'macao',
  madagascar: 'madagascar',
  malawi: 'malawi',
  malaysia: 'malaysia',
  maldives: 'maldives',
  mali: 'mali',
  malta: 'malta',
  marshallIslands: 'marshallIslands',
  martinique: 'martinique',
  mauritania: 'mauritania',
  mauritius: 'mauritius',
  mayotte: 'mayotte',
  mexico: 'mexico',
  micronesia: 'micronesia',
  middleEast: 'middleEast',
  moldova: 'moldova',
  monaco: 'monaco',
  mongolia: 'mongolia',
  montenegro: 'montenegro',
  montserrat: 'montserrat',
  morocco2015: 'morocco2015',
  morocco: 'morocco',
  moroccoWesternSahara: 'moroccoWesternSahara',
  mozambique: 'mozambique',
  myanmar: 'myanmar',
  namibia: 'namibia',
  nauru: 'nauru',
  nepal: 'nepal',
  netherlands: 'netherlands',
  newCaledonia: 'newCaledonia',
  newZealand: 'newZealand',
  nicaragua: 'nicaragua',
  niger: 'niger',
  nigeria: 'nigeria',
  niue: 'niue',
  northAmerica: 'northAmerica',
  northAmericaNoGreenland: 'northAmericaNoGreenland',
  northernMarianaIslands: 'northernMarianaIslands',
  northKorea: 'northKorea',
  northMacedonia: 'northMacedonia',
  norway: 'norway',
  oman: 'oman',
  pakistan: 'pakistan',
  palau: 'palau',
  palestine: 'palestine',
  panama: 'panama',
  papuaNewGuinea: 'papuaNewGuinea',
  paraguay: 'paraguay',
  peru: 'peru',
  philippines: 'philippines',
  pitcairnIslands: 'pitcairnIslands',
  poland: 'poland',
  portugal: 'portugal',
  portugalRegions: 'portugalRegions',
  puertoRico: 'puertoRico',
  qatar: 'qatar',
  reunion: 'reunion',
  romania: 'romania',
  russia: 'russia',
  rwanda: 'rwanda',
  saintMartin: 'saintMartin',
  samoa: 'samoa',
  sanMarino: 'sanMarino',
  saoTomeAndPrincipe: 'saoTomeAndPrincipe',
  saudiArabia: 'saudiArabia',
  senegal: 'senegal',
  serbia: 'serbia',
  serbiaNoKosovo: 'serbiaNoKosovo',
  seychelles: 'seychelles',
  sierraLeone: 'sierraLeone',
  singapore: 'singapore',
  sintMaarten: 'sintMaarten',
  slovakia: 'slovakia',
  slovenia: 'slovenia',
  solomonIslands: 'solomonIslands',
  somalia: 'somalia',
  southAfrica: 'southAfrica',
  southAmerica: 'southAmerica',
  southKorea: 'southKorea',
  southSudan: 'southSudan',
  spain: 'spain',
  spainProvinces: 'spainProvinces',
  sriLanka: 'sriLanka',
  stHelena: 'stHelena',
  stKittsAndNevis: 'stKittsAndNevis',
  stLucia: 'stLucia',
  sudan: 'sudan',
  suriname: 'suriname',
  svalbardAndJanMayen: 'svalbardAndJanMayen',
  sweden: 'sweden',
  switzerland: 'switzerland',
  syria: 'syria',
  taiwan: 'taiwan',
  tajikistan: 'tajikistan',
  tanzania: 'tanzania',
  thailand: 'thailand',
  tibet: 'tibet',
  togo: 'togo',
  tokelau: 'tokelau',
  tonga: 'tonga',
  trinidadAndTobago: 'trinidadAndTobago',
  tunisia: 'tunisia',
  turkey: 'turkey',
  turkmenistan: 'turkmenistan',
  turksAndCaicosIslands: 'turksAndCaicosIslands',
  tuvalu: 'tuvalu',
  uganda: 'uganda',
  ukraine: 'ukraine',
  unitedArabEmirates: 'unitedArabEmirates',
  unitedKingdom: 'unitedKingdom',
  unRegions: 'unRegions',
  uruguay: 'uruguay',
  usa: 'usa',
  usaMercator: 'usaMercator',
  usaTerritoriesAssociatedStates: 'usaTerritoriesAssociatedStates',
  usaTerritories: 'usaTerritories',
  usVirginIslands: 'usVirginIslands',
  uzbekistan: 'uzbekistan',
  vanuatu: 'vanuatu',
  venezuela: 'venezuela',
  vietnam: 'vietnam',
  wallisAndFutuna: 'wallisAndFutuna',
  worldAntarctica: 'worldAntarctica',
  world: 'world',
  worldIndia: 'worldIndia',
  worldPacificRim: 'worldPacificRim',
  worldRussiaSplit: 'worldRussiaSplit',
  yemen: 'yemen',
  zambia: 'zambia',
  zimbabwe: 'zimbabwe',
} as const;

export const REGION_OPTIONS: DefaultOptionType[] = [
  { value: REGION_IDS.afghanistan, label: 'Afghanistan', mapFile: 'afghanistan.svg' },
  { value: REGION_IDS.africa, label: 'Africa', mapFile: 'africa.svg' },
  { value: REGION_IDS.albania, label: 'Albania', mapFile: 'albania.svg' },
  { value: REGION_IDS.algeria, label: 'Algeria', mapFile: 'algeria.svg' },
  {
    value: REGION_IDS.americanSamoa,
    label: 'American Samoa',
    mapFile: 'americanSamoa.svg',
  },
  { value: REGION_IDS.andorra, label: 'Andorra', mapFile: 'andorra.svg' },
  { value: REGION_IDS.angola, label: 'Angola', mapFile: 'angola.svg' },
  { value: REGION_IDS.anguilla, label: 'Anguilla', mapFile: 'anguilla.svg' },
  {
    value: REGION_IDS.antiguaAndBarbuda,
    label: 'Antigua and Barbuda',
    mapFile: 'antiguaAndBarbuda.svg',
  },
  { value: REGION_IDS.argentina, label: 'Argentina', mapFile: 'argentina.svg' },
  { value: REGION_IDS.armenia, label: 'Armenia', mapFile: 'armenia.svg' },
  { value: REGION_IDS.aruba, label: 'Aruba', mapFile: 'aruba.svg' },
  { value: REGION_IDS.asia, label: 'Asia', mapFile: 'asia.svg' },
  { value: REGION_IDS.australia, label: 'Australia', mapFile: 'australia.svg' },
  {
    value: REGION_IDS.australiaOceania,
    label: 'Australia & Oceania',
    mapFile: 'australiaOceania.svg',
  },
  { value: REGION_IDS.austria, label: 'Austria', mapFile: 'austria.svg' },
  { value: REGION_IDS.azerbaijan, label: 'Azerbaijan', mapFile: 'azerbaijan.svg' },
  { value: REGION_IDS.bahamas, label: 'Bahamas', mapFile: 'bahamas.svg' },
  { value: REGION_IDS.bahrain, label: 'Bahrain', mapFile: 'bahrain.svg' },
  { value: REGION_IDS.bangladesh, label: 'Bangladesh', mapFile: 'bangladesh.svg' },
  { value: REGION_IDS.barbados, label: 'Barbados', mapFile: 'barbados.svg' },
  { value: REGION_IDS.belarus, label: 'Belarus', mapFile: 'belarus.svg' },
  { value: REGION_IDS.belgium, label: 'Belgium', mapFile: 'belgium.svg' },
  { value: REGION_IDS.belize, label: 'Belize', mapFile: 'belize.svg' },
  { value: REGION_IDS.benin, label: 'Benin', mapFile: 'benin.svg' },
  { value: REGION_IDS.bermuda, label: 'Bermuda', mapFile: 'bermuda.svg' },
  { value: REGION_IDS.bhutan, label: 'Bhutan', mapFile: 'bhutan.svg' },
  { value: REGION_IDS.bolivia, label: 'Bolivia', mapFile: 'bolivia.svg' },
  {
    value: REGION_IDS.bosniaHerzegovinaCantons,
    label: 'Bosnia & Herzegovina (Cantons)',
    mapFile: 'bosniaHerzegovinaCantons.svg',
  },
  {
    value: REGION_IDS.bosniaHerzegovinaRegions,
    label: 'Bosnia & Herzegovina (Regions)',
    mapFile: 'bosniaHerzegovinaRegions.svg',
  },
  { value: REGION_IDS.botswana, label: 'Botswana', mapFile: 'botswana.svg' },
  { value: REGION_IDS.brazil, label: 'Brazil', mapFile: 'brazil.svg' },
  {
    value: REGION_IDS.britishVirginIslands,
    label: 'British Virgin Islands',
    mapFile: 'britishVirginIslands.svg',
  },
  {
    value: REGION_IDS.bruneiDarussalam,
    label: 'Brunei Darussalam',
    mapFile: 'bruneiDarussalam.svg',
  },
  { value: REGION_IDS.bulgaria, label: 'Bulgaria', mapFile: 'bulgaria.svg' },
  { value: REGION_IDS.burkinaFaso, label: 'Burkina Faso', mapFile: 'burkinaFaso.svg' },
  { value: REGION_IDS.burundi, label: 'Burundi', mapFile: 'burundi.svg' },
  { value: REGION_IDS.cambodia, label: 'Cambodia', mapFile: 'cambodia.svg' },
  { value: REGION_IDS.cameroon, label: 'Cameroon', mapFile: 'cameroon.svg' },
  { value: REGION_IDS.canada, label: 'Canada', mapFile: 'canada.svg' },
  { value: REGION_IDS.capeVerde, label: 'Cape Verde', mapFile: 'capeVerde.svg' },
  { value: REGION_IDS.caribbean, label: 'Caribbean', mapFile: 'caribbean.svg' },
  {
    value: REGION_IDS.caribbeanNetherlands,
    label: 'Caribbean Netherlands',
    mapFile: 'caribbeanNetherlands.svg',
  },
  {
    value: REGION_IDS.caymanIslands,
    label: 'Cayman Islands',
    mapFile: 'caymanIslands.svg',
  },
  {
    value: REGION_IDS.centralAfricanRepublic,
    label: 'Central African Republic',
    mapFile: 'centralAfricanRepublic.svg',
  },
  {
    value: REGION_IDS.centralAmerica,
    label: 'Central America',
    mapFile: 'centralAmerica.svg',
  },
  { value: REGION_IDS.chad, label: 'Chad', mapFile: 'chad.svg' },
  {
    value: REGION_IDS.channelIslands,
    label: 'Channel Islands',
    mapFile: 'channelIslands.svg',
  },
  { value: REGION_IDS.chile, label: 'Chile', mapFile: 'chile.svg' },
  { value: REGION_IDS.china, label: 'China', mapFile: 'china.svg' },
  {
    value: REGION_IDS.christmasIsland,
    label: 'Christmas Island',
    mapFile: 'christmasIsland.svg',
  },
  { value: REGION_IDS.cocosIslands, label: 'Cocos Islands', mapFile: 'cocosIslands.svg' },
  { value: REGION_IDS.colombia, label: 'Colombia', mapFile: 'colombia.svg' },
  { value: REGION_IDS.comoros, label: 'Comoros', mapFile: 'comoros.svg' },
  { value: REGION_IDS.congoDR, label: 'Congo (DR)', mapFile: 'congoDR.svg' },
  { value: REGION_IDS.congo, label: 'Congo', mapFile: 'congo.svg' },
  {
    value: REGION_IDS.continentsRegions,
    label: 'Continents & Regions',
    mapFile: 'continentsRegions.svg',
  },
  {
    value: REGION_IDS.continentsRussiaAntarctica,
    label: 'Continents (Russia & Antarctica)',
    mapFile: 'continentsRussiaAntarctica.svg',
  },
  { value: REGION_IDS.cookIslands, label: 'Cook Islands', mapFile: 'cookIslands.svg' },
  { value: REGION_IDS.costaRica, label: 'Costa Rica', mapFile: 'costaRica.svg' },
  { value: REGION_IDS.croatia, label: 'Croatia', mapFile: 'croatia.svg' },
  { value: REGION_IDS.cuba, label: 'Cuba', mapFile: 'cuba.svg' },
  { value: REGION_IDS.curacao, label: 'Curaçao', mapFile: 'curacao.svg' },
  { value: REGION_IDS.cyprus, label: 'Cyprus', mapFile: 'cyprus.svg' },
  {
    value: REGION_IDS.cyprusNorthernCyprus,
    label: 'Cyprus & Northern Cyprus',
    mapFile: 'cyprusNorthernCyprus.svg',
  },
  {
    value: REGION_IDS.czechRepublic,
    label: 'Czech Republic',
    mapFile: 'czechRepublic.svg',
  },
  { value: REGION_IDS.denmark, label: 'Denmark', mapFile: 'denmark.svg' },
  { value: REGION_IDS.djibouti, label: 'Djibouti', mapFile: 'djibouti.svg' },
  { value: REGION_IDS.dominica, label: 'Dominica', mapFile: 'dominica.svg' },
  {
    value: REGION_IDS.dominicanRepublic,
    label: 'Dominican Republic',
    mapFile: 'dominicanRepublic.svg',
  },
  { value: REGION_IDS.eastTimor, label: 'East Timor', mapFile: 'eastTimor.svg' },
  { value: REGION_IDS.ecuador, label: 'Ecuador', mapFile: 'ecuador.svg' },
  { value: REGION_IDS.egypt, label: 'Egypt', mapFile: 'egypt.svg' },
  { value: REGION_IDS.elSalvador, label: 'El Salvador', mapFile: 'elSalvador.svg' },
  {
    value: REGION_IDS.equatorialGuinea,
    label: 'Equatorial Guinea',
    mapFile: 'equatorialGuinea.svg',
  },
  { value: REGION_IDS.eritrea, label: 'Eritrea', mapFile: 'eritrea.svg' },
  { value: REGION_IDS.estonia, label: 'Estonia', mapFile: 'estonia.svg' },
  { value: REGION_IDS.eSwatini, label: 'Eswatini', mapFile: 'eSwatini.svg' },
  { value: REGION_IDS.ethiopia, label: 'Ethiopia', mapFile: 'ethiopia.svg' },
  { value: REGION_IDS.europe, label: 'Europe', mapFile: 'europe.svg' },
  {
    value: REGION_IDS.falklandIslands,
    label: 'Falkland Islands',
    mapFile: 'falklandIslands.svg',
  },
  { value: REGION_IDS.faroeIslands, label: 'Faroe Islands', mapFile: 'faroeIslands.svg' },
  { value: REGION_IDS.fijiEast, label: 'Fiji (East)', mapFile: 'fijiEast.svg' },
  { value: REGION_IDS.fijiWest, label: 'Fiji (West)', mapFile: 'fijiWest.svg' },
  { value: REGION_IDS.finland, label: 'Finland', mapFile: 'finland.svg' },
  {
    value: REGION_IDS.france2016,
    label: 'France (2016 Regions)',
    mapFile: 'france2016.svg',
  },
  {
    value: REGION_IDS.franceDepartments,
    label: 'France (Departments)',
    mapFile: 'franceDepartments.svg',
  },
  { value: REGION_IDS.france, label: 'France', mapFile: 'france.svg' },
  { value: REGION_IDS.frenchGuiana, label: 'French Guiana', mapFile: 'frenchGuiana.svg' },
  {
    value: REGION_IDS.frenchPolynesia,
    label: 'French Polynesia',
    mapFile: 'frenchPolynesia.svg',
  },
  { value: REGION_IDS.gabon, label: 'Gabon', mapFile: 'gabon.svg' },
  { value: REGION_IDS.gambia, label: 'Gambia', mapFile: 'gambia.svg' },
  { value: REGION_IDS.georgia, label: 'Georgia', mapFile: 'georgia.svg' },
  {
    value: REGION_IDS.georgiaWithSouthOssetia,
    label: 'Georgia (with South Ossetia)',
    mapFile: 'georgiaWithSouthOssetia.svg',
  },
  { value: REGION_IDS.germany, label: 'Germany', mapFile: 'germany.svg' },
  { value: REGION_IDS.ghana, label: 'Ghana', mapFile: 'ghana.svg' },
  { value: REGION_IDS.gibraltar, label: 'Gibraltar', mapFile: 'gibraltar.svg' },
  { value: REGION_IDS.greece, label: 'Greece', mapFile: 'greece.svg' },
  { value: REGION_IDS.greenland, label: 'Greenland', mapFile: 'greenland.svg' },
  { value: REGION_IDS.grenada, label: 'Grenada', mapFile: 'grenada.svg' },
  { value: REGION_IDS.guadeloupe, label: 'Guadeloupe', mapFile: 'guadeloupe.svg' },
  { value: REGION_IDS.guam, label: 'Guam', mapFile: 'guam.svg' },
  { value: REGION_IDS.guatemala, label: 'Guatemala', mapFile: 'guatemala.svg' },
  { value: REGION_IDS.guineaBissau, label: 'Guinea-Bissau', mapFile: 'guineaBissau.svg' },
  { value: REGION_IDS.guinea, label: 'Guinea', mapFile: 'guinea.svg' },
  { value: REGION_IDS.guyana, label: 'Guyana', mapFile: 'guyana.svg' },
  { value: REGION_IDS.haiti, label: 'Haiti', mapFile: 'haiti.svg' },
  { value: REGION_IDS.honduras, label: 'Honduras', mapFile: 'honduras.svg' },
  { value: REGION_IDS.hongKong, label: 'Hong Kong', mapFile: 'hongKong.svg' },
  { value: REGION_IDS.hungary, label: 'Hungary', mapFile: 'hungary.svg' },
  { value: REGION_IDS.iceland, label: 'Iceland', mapFile: 'iceland.svg' },
  {
    value: REGION_IDS.india2019,
    label: 'India (2019 Borders)',
    mapFile: 'india2019.svg',
  },
  { value: REGION_IDS.india, label: 'India', mapFile: 'india.svg' },
  { value: REGION_IDS.indonesia, label: 'Indonesia', mapFile: 'indonesia.svg' },
  { value: REGION_IDS.iran, label: 'Iran', mapFile: 'iran.svg' },
  { value: REGION_IDS.iraq, label: 'Iraq', mapFile: 'iraq.svg' },
  { value: REGION_IDS.ireland, label: 'Ireland', mapFile: 'ireland.svg' },
  { value: REGION_IDS.isleOfMan, label: 'Isle of Man', mapFile: 'isleOfMan.svg' },
  { value: REGION_IDS.israel, label: 'Israel', mapFile: 'israel.svg' },
  {
    value: REGION_IDS.israelPalestine,
    label: 'Israel & Palestine',
    mapFile: 'israelPalestine.svg',
  },
  { value: REGION_IDS.italy, label: 'Italy', mapFile: 'italy.svg' },
  { value: REGION_IDS.ivoryCoast, label: 'Ivory Coast', mapFile: 'ivoryCoast.svg' },
  { value: REGION_IDS.jamaica, label: 'Jamaica', mapFile: 'jamaica.svg' },
  { value: REGION_IDS.japan, label: 'Japan', mapFile: 'japan.svg' },
  { value: REGION_IDS.jersey, label: 'Jersey', mapFile: 'jersey.svg' },
  { value: REGION_IDS.jordan, label: 'Jordan', mapFile: 'jordan.svg' },
  { value: REGION_IDS.kazakhstan, label: 'Kazakhstan', mapFile: 'kazakhstan.svg' },
  { value: REGION_IDS.kenya, label: 'Kenya', mapFile: 'kenya.svg' },
  { value: REGION_IDS.kiribati, label: 'Kiribati', mapFile: 'kiribati.svg' },
  { value: REGION_IDS.kosovo, label: 'Kosovo', mapFile: 'kosovo.svg' },
  { value: REGION_IDS.kuwait, label: 'Kuwait', mapFile: 'kuwait.svg' },
  { value: REGION_IDS.kyrgyzstan, label: 'Kyrgyzstan', mapFile: 'kyrgyzstan.svg' },
  { value: REGION_IDS.laos, label: 'Laos', mapFile: 'laos.svg' },
  { value: REGION_IDS.latinAmerica, label: 'Latin America', mapFile: 'latinAmerica.svg' },
  { value: REGION_IDS.latvia, label: 'Latvia', mapFile: 'latvia.svg' },
  { value: REGION_IDS.lebanon, label: 'Lebanon', mapFile: 'lebanon.svg' },
  { value: REGION_IDS.lesotho, label: 'Lesotho', mapFile: 'lesotho.svg' },
  { value: REGION_IDS.liberia, label: 'Liberia', mapFile: 'liberia.svg' },
  { value: REGION_IDS.libya, label: 'Libya', mapFile: 'libya.svg' },
  {
    value: REGION_IDS.liechtenstein,
    label: 'Liechtenstein',
    mapFile: 'liechtenstein.svg',
  },
  { value: REGION_IDS.lithuania, label: 'Lithuania', mapFile: 'lithuania.svg' },
  { value: REGION_IDS.luxembourg, label: 'Luxembourg', mapFile: 'luxembourg.svg' },
  { value: REGION_IDS.macao, label: 'Macao', mapFile: 'macao.svg' },
  { value: REGION_IDS.madagascar, label: 'Madagascar', mapFile: 'madagascar.svg' },
  { value: REGION_IDS.malawi, label: 'Malawi', mapFile: 'malawi.svg' },
  { value: REGION_IDS.malaysia, label: 'Malaysia', mapFile: 'malaysia.svg' },
  { value: REGION_IDS.maldives, label: 'Maldives', mapFile: 'maldives.svg' },
  { value: REGION_IDS.mali, label: 'Mali', mapFile: 'mali.svg' },
  { value: REGION_IDS.malta, label: 'Malta', mapFile: 'malta.svg' },
  {
    value: REGION_IDS.marshallIslands,
    label: 'Marshall Islands',
    mapFile: 'marshallIslands.svg',
  },
  { value: REGION_IDS.martinique, label: 'Martinique', mapFile: 'martinique.svg' },
  { value: REGION_IDS.mauritania, label: 'Mauritania', mapFile: 'mauritania.svg' },
  { value: REGION_IDS.mauritius, label: 'Mauritius', mapFile: 'mauritius.svg' },
  { value: REGION_IDS.mayotte, label: 'Mayotte', mapFile: 'mayotte.svg' },
  { value: REGION_IDS.mexico, label: 'Mexico', mapFile: 'mexico.svg' },
  { value: REGION_IDS.micronesia, label: 'Micronesia', mapFile: 'micronesia.svg' },
  { value: REGION_IDS.middleEast, label: 'Middle East', mapFile: 'middleEast.svg' },
  { value: REGION_IDS.moldova, label: 'Moldova', mapFile: 'moldova.svg' },
  { value: REGION_IDS.monaco, label: 'Monaco', mapFile: 'monaco.svg' },
  { value: REGION_IDS.mongolia, label: 'Mongolia', mapFile: 'mongolia.svg' },
  { value: REGION_IDS.montenegro, label: 'Montenegro', mapFile: 'montenegro.svg' },
  { value: REGION_IDS.montserrat, label: 'Montserrat', mapFile: 'montserrat.svg' },
  {
    value: REGION_IDS.morocco2015,
    label: 'Morocco (2015 Regions)',
    mapFile: 'morocco2015.svg',
  },
  { value: REGION_IDS.morocco, label: 'Morocco', mapFile: 'morocco.svg' },
  {
    value: REGION_IDS.moroccoWesternSahara,
    label: 'Morocco & Western Sahara',
    mapFile: 'moroccoWesternSahara.svg',
  },
  { value: REGION_IDS.mozambique, label: 'Mozambique', mapFile: 'mozambique.svg' },
  { value: REGION_IDS.myanmar, label: 'Myanmar', mapFile: 'myanmar.svg' },
  { value: REGION_IDS.namibia, label: 'Namibia', mapFile: 'namibia.svg' },
  { value: REGION_IDS.nauru, label: 'Nauru', mapFile: 'nauru.svg' },
  { value: REGION_IDS.nepal, label: 'Nepal', mapFile: 'nepal.svg' },
  { value: REGION_IDS.netherlands, label: 'Netherlands', mapFile: 'netherlands.svg' },
  { value: REGION_IDS.newCaledonia, label: 'New Caledonia', mapFile: 'newCaledonia.svg' },
  { value: REGION_IDS.newZealand, label: 'New Zealand', mapFile: 'newZealand.svg' },
  { value: REGION_IDS.nicaragua, label: 'Nicaragua', mapFile: 'nicaragua.svg' },
  { value: REGION_IDS.niger, label: 'Niger', mapFile: 'niger.svg' },
  { value: REGION_IDS.nigeria, label: 'Nigeria', mapFile: 'nigeria.svg' },
  { value: REGION_IDS.niue, label: 'Niue', mapFile: 'niue.svg' },
  { value: REGION_IDS.northAmerica, label: 'North America', mapFile: 'northAmerica.svg' },
  {
    value: REGION_IDS.northAmericaNoGreenland,
    label: 'North America (No Greenland)',
    mapFile: 'northAmericaNoGreenland.svg',
  },
  {
    value: REGION_IDS.northernMarianaIslands,
    label: 'Northern Mariana Islands',
    mapFile: 'northernMarianaIslands.svg',
  },
  { value: REGION_IDS.northKorea, label: 'North Korea', mapFile: 'northKorea.svg' },
  {
    value: REGION_IDS.northMacedonia,
    label: 'North Macedonia',
    mapFile: 'northMacedonia.svg',
  },
  { value: REGION_IDS.norway, label: 'Norway', mapFile: 'norway.svg' },
  { value: REGION_IDS.oman, label: 'Oman', mapFile: 'oman.svg' },
  { value: REGION_IDS.pakistan, label: 'Pakistan', mapFile: 'pakistan.svg' },
  { value: REGION_IDS.palau, label: 'Palau', mapFile: 'palau.svg' },
  { value: REGION_IDS.palestine, label: 'Palestine', mapFile: 'palestine.svg' },
  { value: REGION_IDS.panama, label: 'Panama', mapFile: 'panama.svg' },
  {
    value: REGION_IDS.papuaNewGuinea,
    label: 'Papua New Guinea',
    mapFile: 'papuaNewGuinea.svg',
  },
  { value: REGION_IDS.paraguay, label: 'Paraguay', mapFile: 'paraguay.svg' },
  { value: REGION_IDS.peru, label: 'Peru', mapFile: 'peru.svg' },
  { value: REGION_IDS.philippines, label: 'Philippines', mapFile: 'philippines.svg' },
  {
    value: REGION_IDS.pitcairnIslands,
    label: 'Pitcairn Islands',
    mapFile: 'pitcairnIslands.svg',
  },
  { value: REGION_IDS.poland, label: 'Poland', mapFile: 'poland.svg' },
  { value: REGION_IDS.portugal, label: 'Portugal', mapFile: 'portugal.svg' },
  {
    value: REGION_IDS.portugalRegions,
    label: 'Portugal (Regions)',
    mapFile: 'portugalRegions.svg',
  },
  { value: REGION_IDS.puertoRico, label: 'Puerto Rico', mapFile: 'puertoRico.svg' },
  { value: REGION_IDS.qatar, label: 'Qatar', mapFile: 'qatar.svg' },
  { value: REGION_IDS.reunion, label: 'Réunion', mapFile: 'reunion.svg' },
  { value: REGION_IDS.romania, label: 'Romania', mapFile: 'romania.svg' },
  { value: REGION_IDS.russia, label: 'Russia', mapFile: 'russia.svg' },
  { value: REGION_IDS.rwanda, label: 'Rwanda', mapFile: 'rwanda.svg' },
  { value: REGION_IDS.saintMartin, label: 'Saint Martin', mapFile: 'saintMartin.svg' },
  { value: REGION_IDS.samoa, label: 'Samoa', mapFile: 'samoa.svg' },
  { value: REGION_IDS.sanMarino, label: 'San Marino', mapFile: 'sanMarino.svg' },
  {
    value: REGION_IDS.saoTomeAndPrincipe,
    label: 'São Tomé and Príncipe',
    mapFile: 'saoTomeAndPrincipe.svg',
  },
  { value: REGION_IDS.saudiArabia, label: 'Saudi Arabia', mapFile: 'saudiArabia.svg' },
  { value: REGION_IDS.senegal, label: 'Senegal', mapFile: 'senegal.svg' },
  { value: REGION_IDS.serbia, label: 'Serbia', mapFile: 'serbia.svg' },
  {
    value: REGION_IDS.serbiaNoKosovo,
    label: 'Serbia (No Kosovo)',
    mapFile: 'serbiaNoKosovo.svg',
  },
  { value: REGION_IDS.seychelles, label: 'Seychelles', mapFile: 'seychelles.svg' },
  { value: REGION_IDS.sierraLeone, label: 'Sierra Leone', mapFile: 'sierraLeone.svg' },
  { value: REGION_IDS.singapore, label: 'Singapore', mapFile: 'singapore.svg' },
  { value: REGION_IDS.sintMaarten, label: 'Sint Maarten', mapFile: 'sintMaarten.svg' },
  { value: REGION_IDS.slovakia, label: 'Slovakia', mapFile: 'slovakia.svg' },
  { value: REGION_IDS.slovenia, label: 'Slovenia', mapFile: 'slovenia.svg' },
  {
    value: REGION_IDS.solomonIslands,
    label: 'Solomon Islands',
    mapFile: 'solomonIslands.svg',
  },
  { value: REGION_IDS.somalia, label: 'Somalia', mapFile: 'somalia.svg' },
  { value: REGION_IDS.southAfrica, label: 'South Africa', mapFile: 'southAfrica.svg' },
  { value: REGION_IDS.southAmerica, label: 'South America', mapFile: 'southAmerica.svg' },
  { value: REGION_IDS.southKorea, label: 'South Korea', mapFile: 'southKorea.svg' },
  { value: REGION_IDS.southSudan, label: 'South Sudan', mapFile: 'southSudan.svg' },
  { value: REGION_IDS.spain, label: 'Spain', mapFile: 'spain.svg' },
  {
    value: REGION_IDS.spainProvinces,
    label: 'Spain (Provinces)',
    mapFile: 'spainProvinces.svg',
  },
  { value: REGION_IDS.sriLanka, label: 'Sri Lanka', mapFile: 'sriLanka.svg' },
  { value: REGION_IDS.stHelena, label: 'St. Helena', mapFile: 'stHelena.svg' },
  {
    value: REGION_IDS.stKittsAndNevis,
    label: 'St. Kitts and Nevis',
    mapFile: 'stKittsAndNevis.svg',
  },
  { value: REGION_IDS.stLucia, label: 'St. Lucia', mapFile: 'stLucia.svg' },
  { value: REGION_IDS.sudan, label: 'Sudan', mapFile: 'sudan.svg' },
  { value: REGION_IDS.suriname, label: 'Suriname', mapFile: 'suriname.svg' },
  {
    value: REGION_IDS.svalbardAndJanMayen,
    label: 'Svalbard and Jan Mayen',
    mapFile: 'svalbardAndJanMayen.svg',
  },
  { value: REGION_IDS.sweden, label: 'Sweden', mapFile: 'sweden.svg' },
  { value: REGION_IDS.switzerland, label: 'Switzerland', mapFile: 'switzerland.svg' },
  { value: REGION_IDS.syria, label: 'Syria', mapFile: 'syria.svg' },
  { value: REGION_IDS.taiwan, label: 'Taiwan', mapFile: 'taiwan.svg' },
  { value: REGION_IDS.tajikistan, label: 'Tajikistan', mapFile: 'tajikistan.svg' },
  { value: REGION_IDS.tanzania, label: 'Tanzania', mapFile: 'tanzania.svg' },
  { value: REGION_IDS.thailand, label: 'Thailand', mapFile: 'thailand.svg' },
  { value: REGION_IDS.tibet, label: 'Tibet', mapFile: 'tibet.svg' },
  { value: REGION_IDS.togo, label: 'Togo', mapFile: 'togo.svg' },
  { value: REGION_IDS.tokelau, label: 'Tokelau', mapFile: 'tokelau.svg' },
  { value: REGION_IDS.tonga, label: 'Tonga', mapFile: 'tonga.svg' },
  {
    value: REGION_IDS.trinidadAndTobago,
    label: 'Trinidad and Tobago',
    mapFile: 'trinidadAndTobago.svg',
  },
  { value: REGION_IDS.tunisia, label: 'Tunisia', mapFile: 'tunisia.svg' },
  { value: REGION_IDS.turkey, label: 'Turkey', mapFile: 'turkey.svg' },
  { value: REGION_IDS.turkmenistan, label: 'Turkmenistan', mapFile: 'turkmenistan.svg' },
  {
    value: REGION_IDS.turksAndCaicosIslands,
    label: 'Turks and Caicos Islands',
    mapFile: 'turksAndCaicosIslands.svg',
  },
  { value: REGION_IDS.tuvalu, label: 'Tuvalu', mapFile: 'tuvalu.svg' },
  { value: REGION_IDS.uganda, label: 'Uganda', mapFile: 'uganda.svg' },
  { value: REGION_IDS.ukraine, label: 'Ukraine', mapFile: 'ukraine.svg' },
  {
    value: REGION_IDS.unitedArabEmirates,
    label: 'United Arab Emirates',
    mapFile: 'unitedArabEmirates.svg',
  },
  {
    value: REGION_IDS.unitedKingdom,
    label: 'United Kingdom',
    mapFile: 'unitedKingdom.svg',
  },
  { value: REGION_IDS.unRegions, label: 'UN Regions', mapFile: 'unRegions.svg' },
  { value: REGION_IDS.uruguay, label: 'Uruguay', mapFile: 'uruguay.svg' },
  { value: REGION_IDS.usa, label: 'United States', mapFile: 'usa.svg' },
  {
    value: REGION_IDS.usaMercator,
    label: 'United States (Mercator)',
    mapFile: 'usaMercator.svg',
  },
  {
    value: REGION_IDS.usaTerritoriesAssociatedStates,
    label: 'USA Territories & Associated States',
    mapFile: 'usaTerritoriesAssociatedStates.svg',
  },
  {
    value: REGION_IDS.usaTerritories,
    label: 'USA Territories',
    mapFile: 'usaTerritories.svg',
  },
  {
    value: REGION_IDS.usVirginIslands,
    label: 'US Virgin Islands',
    mapFile: 'usVirginIslands.svg',
  },
  { value: REGION_IDS.uzbekistan, label: 'Uzbekistan', mapFile: 'uzbekistan.svg' },
  { value: REGION_IDS.vanuatu, label: 'Vanuatu', mapFile: 'vanuatu.svg' },
  { value: REGION_IDS.venezuela, label: 'Venezuela', mapFile: 'venezuela.svg' },
  { value: REGION_IDS.vietnam, label: 'Vietnam', mapFile: 'vietnam.svg' },
  {
    value: REGION_IDS.wallisAndFutuna,
    label: 'Wallis and Futuna',
    mapFile: 'wallisAndFutuna.svg',
  },
  {
    value: REGION_IDS.worldAntarctica,
    label: 'World (with Antarctica)',
    mapFile: 'worldAntarctica.svg',
  },
  { value: REGION_IDS.world, label: 'World', mapFile: 'world.svg' },
  {
    value: REGION_IDS.worldIndia,
    label: 'World (India View)',
    mapFile: 'worldIndia.svg',
  },
  {
    value: REGION_IDS.worldPacificRim,
    label: 'World (Pacific Rim)',
    mapFile: 'worldPacificRim.svg',
  },
  {
    value: REGION_IDS.worldRussiaSplit,
    label: 'World (Russia Split)',
    mapFile: 'worldRussiaSplit.svg',
  },
  { value: REGION_IDS.yemen, label: 'Yemen', mapFile: 'yemen.svg' },
  { value: REGION_IDS.zambia, label: 'Zambia', mapFile: 'zambia.svg' },
  { value: REGION_IDS.zimbabwe, label: 'Zimbabwe', mapFile: 'zimbabwe.svg' },
];
