import type { DefaultOptionType } from 'antd/es/select';

export const JURISDICTION_IDS = {
  afghanistan: 'afghanistan',
  africa: 'africa',
  albania: 'albania',
  algeria: 'algeria',
  americanSamoa: 'americanSamoa',
  andorra: 'andorra',
  angola: 'angola',
  anguilla: 'anguilla',
  antiguaAndBarbuda: 'antiguaAndBarbuda',
  argentina: 'argentina',
  armenia: 'armenia',
  aruba: 'aruba',
  asia: 'asia',
  australia: 'australia',
  australiaOceania: 'australiaOceania',
  austria: 'austria',
  azerbaijan: 'azerbaijan',
  bahamas: 'bahamas',
  bahrain: 'bahrain',
  bangladesh: 'bangladesh',
  barbados: 'barbados',
  belarus: 'belarus',
  belgium: 'belgium',
  belize: 'belize',
  benin: 'benin',
  bermuda: 'bermuda',
  bhutan: 'bhutan',
  bolivia: 'bolivia',
  bosniaHerzegovinaCantons: 'bosniaHerzegovinaCantons',
  bosniaHerzegovinaRegions: 'bosniaHerzegovinaRegions',
  botswana: 'botswana',
  brazil: 'brazil',
  britishVirginIslands: 'britishVirginIslands',
  bruneiDarussalam: 'bruneiDarussalam',
  bulgaria: 'bulgaria',
  burkinaFaso: 'burkinaFaso',
  burundi: 'burundi',
  cambodia: 'cambodia',
  cameroon: 'cameroon',
  canada: 'canada',
  capeVerde: 'capeVerde',
  caribbean: 'caribbean',
  caribbeanNetherlands: 'caribbeanNetherlands',
  caymanIslands: 'caymanIslands',
  centralAfricanRepublic: 'centralAfricanRepublic',
  centralAmerica: 'centralAmerica',
  chad: 'chad',
  channelIslands: 'channelIslands',
  chile: 'chile',
  china: 'china',
  christmasIsland: 'christmasIsland',
  cocosIslands: 'cocosIslands',
  colombia: 'colombia',
  comoros: 'comoros',
  congoDR: 'congoDR',
  congo: 'congo',
  continentsRegions: 'continentsRegions',
  continentsRussiaAntarctica: 'continentsRussiaAntarctica',
  cookIslands: 'cookIslands',
  costaRica: 'costaRica',
  croatia: 'croatia',
  cuba: 'cuba',
  curacao: 'curacao',
  cyprus: 'cyprus',
  cyprusNorthernCyprus: 'cyprusNorthernCyprus',
  czechRepublic: 'czechRepublic',
  denmark: 'denmark',
  djibouti: 'djibouti',
  dominica: 'dominica',
  dominicanRepublic: 'dominicanRepublic',
  eastTimor: 'eastTimor',
  ecuador: 'ecuador',
  egypt: 'egypt',
  elSalvador: 'elSalvador',
  equatorialGuinea: 'equatorialGuinea',
  eritrea: 'eritrea',
  estonia: 'estonia',
  eSwatini: 'eSwatini',
  ethiopia: 'ethiopia',
  europe: 'europe',
  falklandIslands: 'falklandIslands',
  faroeIslands: 'faroeIslands',
  fijiEast: 'fijiEast',
  fijiWest: 'fijiWest',
  finland: 'finland',
  france2016: 'france2016',
  franceDepartments: 'franceDepartments',
  france: 'france',
  frenchGuiana: 'frenchGuiana',
  frenchPolynesia: 'frenchPolynesia',
  gabon: 'gabon',
  gambia: 'gambia',
  georgia: 'georgia',
  georgiaWithSouthOssetia: 'georgiaWithSouthOssetia',
  germany: 'germany',
  ghana: 'ghana',
  gibraltar: 'gibraltar',
  greece: 'greece',
  greenland: 'greenland',
  grenada: 'grenada',
  guadeloupe: 'guadeloupe',
  guam: 'guam',
  guatemala: 'guatemala',
  guineaBissau: 'guineaBissau',
  guinea: 'guinea',
  guyana: 'guyana',
  haiti: 'haiti',
  honduras: 'honduras',
  hongKong: 'hongKong',
  hungary: 'hungary',
  iceland: 'iceland',
  india2019: 'india2019',
  india: 'india',
  indonesia: 'indonesia',
  iran: 'iran',
  iraq: 'iraq',
  ireland: 'ireland',
  isleOfMan: 'isleOfMan',
  israel: 'israel',
  israelPalestine: 'israelPalestine',
  italy: 'italy',
  ivoryCoast: 'ivoryCoast',
  jamaica: 'jamaica',
  japan: 'japan',
  jersey: 'jersey',
  jordan: 'jordan',
  kazakhstan: 'kazakhstan',
  kenya: 'kenya',
  kiribati: 'kiribati',
  kosovo: 'kosovo',
  kuwait: 'kuwait',
  kyrgyzstan: 'kyrgyzstan',
  laos: 'laos',
  latinAmerica: 'latinAmerica',
  latvia: 'latvia',
  lebanon: 'lebanon',
  lesotho: 'lesotho',
  liberia: 'liberia',
  libya: 'libya',
  liechtenstein: 'liechtenstein',
  lithuania: 'lithuania',
  luxembourg: 'luxembourg',
  macao: 'macao',
  madagascar: 'madagascar',
  malawi: 'malawi',
  malaysia: 'malaysia',
  maldives: 'maldives',
  mali: 'mali',
  malta: 'malta',
  marshallIslands: 'marshallIslands',
  martinique: 'martinique',
  mauritania: 'mauritania',
  mauritius: 'mauritius',
  mayotte: 'mayotte',
  mexico: 'mexico',
  micronesia: 'micronesia',
  middleEast: 'middleEast',
  moldova: 'moldova',
  monaco: 'monaco',
  mongolia: 'mongolia',
  montenegro: 'montenegro',
  montserrat: 'montserrat',
  morocco2015: 'morocco2015',
  morocco: 'morocco',
  moroccoWesternSahara: 'moroccoWesternSahara',
  mozambique: 'mozambique',
  myanmar: 'myanmar',
  namibia: 'namibia',
  nauru: 'nauru',
  nepal: 'nepal',
  netherlands: 'netherlands',
  newCaledonia: 'newCaledonia',
  newZealand: 'newZealand',
  nicaragua: 'nicaragua',
  niger: 'niger',
  nigeria: 'nigeria',
  niue: 'niue',
  northAmerica: 'northAmerica',
  northAmericaNoGreenland: 'northAmericaNoGreenland',
  northernMarianaIslands: 'northernMarianaIslands',
  northKorea: 'northKorea',
  northMacedonia: 'northMacedonia',
  norway: 'norway',
  oman: 'oman',
  pakistan: 'pakistan',
  palau: 'palau',
  palestine: 'palestine',
  panama: 'panama',
  papuaNewGuinea: 'papuaNewGuinea',
  paraguay: 'paraguay',
  peru: 'peru',
  philippines: 'philippines',
  pitcairnIslands: 'pitcairnIslands',
  poland: 'poland',
  portugal: 'portugal',
  portugalRegions: 'portugalRegions',
  puertoRico: 'puertoRico',
  qatar: 'qatar',
  reunion: 'reunion',
  romania: 'romania',
  russia: 'russia',
  rwanda: 'rwanda',
  saintMartin: 'saintMartin',
  samoa: 'samoa',
  sanMarino: 'sanMarino',
  saoTomeAndPrincipe: 'saoTomeAndPrincipe',
  saudiArabia: 'saudiArabia',
  senegal: 'senegal',
  serbia: 'serbia',
  serbiaNoKosovo: 'serbiaNoKosovo',
  seychelles: 'seychelles',
  sierraLeone: 'sierraLeone',
  singapore: 'singapore',
  sintMaarten: 'sintMaarten',
  slovakia: 'slovakia',
  slovenia: 'slovenia',
  solomonIslands: 'solomonIslands',
  somalia: 'somalia',
  southAfrica: 'southAfrica',
  southAmerica: 'southAmerica',
  southKorea: 'southKorea',
  southSudan: 'southSudan',
  spain: 'spain',
  spainProvinces: 'spainProvinces',
  sriLanka: 'sriLanka',
  stHelena: 'stHelena',
  stKittsAndNevis: 'stKittsAndNevis',
  stLucia: 'stLucia',
  sudan: 'sudan',
  suriname: 'suriname',
  svalbardAndJanMayen: 'svalbardAndJanMayen',
  sweden: 'sweden',
  switzerland: 'switzerland',
  syria: 'syria',
  taiwan: 'taiwan',
  tajikistan: 'tajikistan',
  tanzania: 'tanzania',
  thailand: 'thailand',
  tibet: 'tibet',
  togo: 'togo',
  tokelau: 'tokelau',
  tonga: 'tonga',
  trinidadAndTobago: 'trinidadAndTobago',
  tunisia: 'tunisia',
  turkey: 'turkey',
  turkmenistan: 'turkmenistan',
  turksAndCaicosIslands: 'turksAndCaicosIslands',
  tuvalu: 'tuvalu',
  uganda: 'uganda',
  ukraine: 'ukraine',
  unitedArabEmirates: 'unitedArabEmirates',
  unitedKingdom: 'unitedKingdom',
  unRegions: 'unRegions',
  uruguay: 'uruguay',
  usa: 'usa',
  usaMercator: 'usaMercator',
  usaTerritoriesAssociatedStates: 'usaTerritoriesAssociatedStates',
  usaTerritories: 'usaTerritories',
  usVirginIslands: 'usVirginIslands',
  uzbekistan: 'uzbekistan',
  vanuatu: 'vanuatu',
  venezuela: 'venezuela',
  vietnam: 'vietnam',
  wallisAndFutuna: 'wallisAndFutuna',
  worldAntarctica: 'worldAntarctica',
  world: 'world',
  worldIndia: 'worldIndia',
  worldPacificRim: 'worldPacificRim',
  worldRussiaSplit: 'worldRussiaSplit',
  yemen: 'yemen',
  zambia: 'zambia',
  zimbabwe: 'zimbabwe',
} as const;

export const JURISDICTION_OPTIONS: DefaultOptionType[] = [
  { value: JURISDICTION_IDS.afghanistan, label: 'Afghanistan', mapFile: 'afghanistanHigh.svg' },
  { value: JURISDICTION_IDS.africa, label: 'Africa', mapFile: 'africaHigh.svg' },
  { value: JURISDICTION_IDS.albania, label: 'Albania', mapFile: 'albaniaHigh.svg' },
  { value: JURISDICTION_IDS.algeria, label: 'Algeria', mapFile: 'algeriaHigh.svg' },
  {
    value: JURISDICTION_IDS.americanSamoa,
    label: 'American Samoa',
    mapFile: 'americanSamoaHigh.svg',
  },
  { value: JURISDICTION_IDS.andorra, label: 'Andorra', mapFile: 'andorraHigh.svg' },
  { value: JURISDICTION_IDS.angola, label: 'Angola', mapFile: 'angolaHigh.svg' },
  { value: JURISDICTION_IDS.anguilla, label: 'Anguilla', mapFile: 'anguillaHigh.svg' },
  {
    value: JURISDICTION_IDS.antiguaAndBarbuda,
    label: 'Antigua and Barbuda',
    mapFile: 'antiguaAndBarbudaHigh.svg',
  },
  { value: JURISDICTION_IDS.argentina, label: 'Argentina', mapFile: 'argentinaHigh.svg' },
  { value: JURISDICTION_IDS.armenia, label: 'Armenia', mapFile: 'armeniaHigh.svg' },
  { value: JURISDICTION_IDS.aruba, label: 'Aruba', mapFile: 'arubaHigh.svg' },
  { value: JURISDICTION_IDS.asia, label: 'Asia', mapFile: 'asiaHigh.svg' },
  { value: JURISDICTION_IDS.australia, label: 'Australia', mapFile: 'australiaHigh.svg' },
  {
    value: JURISDICTION_IDS.australiaOceania,
    label: 'Australia & Oceania',
    mapFile: 'australiaOceaniaHigh.svg',
  },
  { value: JURISDICTION_IDS.austria, label: 'Austria', mapFile: 'austriaHigh.svg' },
  { value: JURISDICTION_IDS.azerbaijan, label: 'Azerbaijan', mapFile: 'azerbaijanHigh.svg' },
  { value: JURISDICTION_IDS.bahamas, label: 'Bahamas', mapFile: 'bahamasHigh.svg' },
  { value: JURISDICTION_IDS.bahrain, label: 'Bahrain', mapFile: 'bahrainHigh.svg' },
  { value: JURISDICTION_IDS.bangladesh, label: 'Bangladesh', mapFile: 'bangladeshHigh.svg' },
  { value: JURISDICTION_IDS.barbados, label: 'Barbados', mapFile: 'barbadosHigh.svg' },
  { value: JURISDICTION_IDS.belarus, label: 'Belarus', mapFile: 'belarusHigh.svg' },
  { value: JURISDICTION_IDS.belgium, label: 'Belgium', mapFile: 'belgiumHigh.svg' },
  { value: JURISDICTION_IDS.belize, label: 'Belize', mapFile: 'belizeHigh.svg' },
  { value: JURISDICTION_IDS.benin, label: 'Benin', mapFile: 'beninHigh.svg' },
  { value: JURISDICTION_IDS.bermuda, label: 'Bermuda', mapFile: 'bermudaHigh.svg' },
  { value: JURISDICTION_IDS.bhutan, label: 'Bhutan', mapFile: 'bhutanHigh.svg' },
  { value: JURISDICTION_IDS.bolivia, label: 'Bolivia', mapFile: 'boliviaHigh.svg' },
  {
    value: JURISDICTION_IDS.bosniaHerzegovinaCantons,
    label: 'Bosnia & Herzegovina (Cantons)',
    mapFile: 'bosniaHerzegovinaCantonsHigh.svg',
  },
  {
    value: JURISDICTION_IDS.bosniaHerzegovinaRegions,
    label: 'Bosnia & Herzegovina (Regions)',
    mapFile: 'bosniaHerzegovinaRegionsHigh.svg',
  },
  { value: JURISDICTION_IDS.botswana, label: 'Botswana', mapFile: 'botswanaHigh.svg' },
  { value: JURISDICTION_IDS.brazil, label: 'Brazil', mapFile: 'brazilHigh.svg' },
  {
    value: JURISDICTION_IDS.britishVirginIslands,
    label: 'British Virgin Islands',
    mapFile: 'britishVirginIslandsHigh.svg',
  },
  {
    value: JURISDICTION_IDS.bruneiDarussalam,
    label: 'Brunei Darussalam',
    mapFile: 'bruneiDarussalamHigh.svg',
  },
  { value: JURISDICTION_IDS.bulgaria, label: 'Bulgaria', mapFile: 'bulgariaHigh.svg' },
  { value: JURISDICTION_IDS.burkinaFaso, label: 'Burkina Faso', mapFile: 'burkinaFasoHigh.svg' },
  { value: JURISDICTION_IDS.burundi, label: 'Burundi', mapFile: 'burundiHigh.svg' },
  { value: JURISDICTION_IDS.cambodia, label: 'Cambodia', mapFile: 'cambodiaHigh.svg' },
  { value: JURISDICTION_IDS.cameroon, label: 'Cameroon', mapFile: 'cameroonHigh.svg' },
  { value: JURISDICTION_IDS.canada, label: 'Canada', mapFile: 'canadaHigh.svg' },
  { value: JURISDICTION_IDS.capeVerde, label: 'Cape Verde', mapFile: 'capeVerdeHigh.svg' },
  { value: JURISDICTION_IDS.caribbean, label: 'Caribbean', mapFile: 'caribbeanHigh.svg' },
  {
    value: JURISDICTION_IDS.caribbeanNetherlands,
    label: 'Caribbean Netherlands',
    mapFile: 'caribbeanNetherlandsHigh.svg',
  },
  {
    value: JURISDICTION_IDS.caymanIslands,
    label: 'Cayman Islands',
    mapFile: 'caymanIslandsHigh.svg',
  },
  {
    value: JURISDICTION_IDS.centralAfricanRepublic,
    label: 'Central African Republic',
    mapFile: 'centralAfricanRepublicHigh.svg',
  },
  {
    value: JURISDICTION_IDS.centralAmerica,
    label: 'Central America',
    mapFile: 'centralAmericaHigh.svg',
  },
  { value: JURISDICTION_IDS.chad, label: 'Chad', mapFile: 'chadHigh.svg' },
  {
    value: JURISDICTION_IDS.channelIslands,
    label: 'Channel Islands',
    mapFile: 'channelIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.chile, label: 'Chile', mapFile: 'chileHigh.svg' },
  { value: JURISDICTION_IDS.china, label: 'China', mapFile: 'chinaHigh.svg' },
  {
    value: JURISDICTION_IDS.christmasIsland,
    label: 'Christmas Island',
    mapFile: 'christmasIslandHigh.svg',
  },
  { value: JURISDICTION_IDS.cocosIslands, label: 'Cocos Islands', mapFile: 'cocosIslandsHigh.svg' },
  { value: JURISDICTION_IDS.colombia, label: 'Colombia', mapFile: 'colombiaHigh.svg' },
  { value: JURISDICTION_IDS.comoros, label: 'Comoros', mapFile: 'comorosHigh.svg' },
  { value: JURISDICTION_IDS.congoDR, label: 'Congo (DR)', mapFile: 'congoDRHigh.svg' },
  { value: JURISDICTION_IDS.congo, label: 'Congo', mapFile: 'congoHigh.svg' },
  {
    value: JURISDICTION_IDS.continentsRegions,
    label: 'Continents & Regions',
    mapFile: 'continentsRegionsHigh.svg',
  },
  {
    value: JURISDICTION_IDS.continentsRussiaAntarctica,
    label: 'Continents (Russia & Antarctica)',
    mapFile: 'continentsRussiaAntarcticaHigh.svg',
  },
  { value: JURISDICTION_IDS.cookIslands, label: 'Cook Islands', mapFile: 'cookIslandsHigh.svg' },
  { value: JURISDICTION_IDS.costaRica, label: 'Costa Rica', mapFile: 'costaRicaHigh.svg' },
  { value: JURISDICTION_IDS.croatia, label: 'Croatia', mapFile: 'croatiaHigh.svg' },
  { value: JURISDICTION_IDS.cuba, label: 'Cuba', mapFile: 'cubaHigh.svg' },
  { value: JURISDICTION_IDS.curacao, label: 'Curaçao', mapFile: 'curacaoHigh.svg' },
  { value: JURISDICTION_IDS.cyprus, label: 'Cyprus', mapFile: 'cyprusHigh.svg' },
  {
    value: JURISDICTION_IDS.cyprusNorthernCyprus,
    label: 'Cyprus & Northern Cyprus',
    mapFile: 'cyprusNorthernCyprusHigh.svg',
  },
  {
    value: JURISDICTION_IDS.czechRepublic,
    label: 'Czech Republic',
    mapFile: 'czechRepublicHigh.svg',
  },
  { value: JURISDICTION_IDS.denmark, label: 'Denmark', mapFile: 'denmarkHigh.svg' },
  { value: JURISDICTION_IDS.djibouti, label: 'Djibouti', mapFile: 'djiboutiHigh.svg' },
  { value: JURISDICTION_IDS.dominica, label: 'Dominica', mapFile: 'dominicaHigh.svg' },
  {
    value: JURISDICTION_IDS.dominicanRepublic,
    label: 'Dominican Republic',
    mapFile: 'dominicanRepublicHigh.svg',
  },
  { value: JURISDICTION_IDS.eastTimor, label: 'East Timor', mapFile: 'eastTimorHigh.svg' },
  { value: JURISDICTION_IDS.ecuador, label: 'Ecuador', mapFile: 'ecuadorHigh.svg' },
  { value: JURISDICTION_IDS.egypt, label: 'Egypt', mapFile: 'egyptHigh.svg' },
  { value: JURISDICTION_IDS.elSalvador, label: 'El Salvador', mapFile: 'elSalvadorHigh.svg' },
  {
    value: JURISDICTION_IDS.equatorialGuinea,
    label: 'Equatorial Guinea',
    mapFile: 'equatorialGuineaHigh.svg',
  },
  { value: JURISDICTION_IDS.eritrea, label: 'Eritrea', mapFile: 'eritreaHigh.svg' },
  { value: JURISDICTION_IDS.estonia, label: 'Estonia', mapFile: 'estoniaHigh.svg' },
  { value: JURISDICTION_IDS.eSwatini, label: 'Eswatini', mapFile: 'eSwatiniHigh.svg' },
  { value: JURISDICTION_IDS.ethiopia, label: 'Ethiopia', mapFile: 'ethiopiaHigh.svg' },
  { value: JURISDICTION_IDS.europe, label: 'Europe', mapFile: 'europeHigh.svg' },
  {
    value: JURISDICTION_IDS.falklandIslands,
    label: 'Falkland Islands',
    mapFile: 'falklandIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.faroeIslands, label: 'Faroe Islands', mapFile: 'faroeIslandsHigh.svg' },
  { value: JURISDICTION_IDS.fijiEast, label: 'Fiji (East)', mapFile: 'fijiEastHigh.svg' },
  { value: JURISDICTION_IDS.fijiWest, label: 'Fiji (West)', mapFile: 'fijiWestHigh.svg' },
  { value: JURISDICTION_IDS.finland, label: 'Finland', mapFile: 'finlandHigh.svg' },
  {
    value: JURISDICTION_IDS.france2016,
    label: 'France (2016 Regions)',
    mapFile: 'france2016High.svg',
  },
  {
    value: JURISDICTION_IDS.franceDepartments,
    label: 'France (Departments)',
    mapFile: 'franceDepartmentsHigh.svg',
  },
  { value: JURISDICTION_IDS.france, label: 'France', mapFile: 'franceHigh.svg' },
  { value: JURISDICTION_IDS.frenchGuiana, label: 'French Guiana', mapFile: 'frenchGuianaHigh.svg' },
  {
    value: JURISDICTION_IDS.frenchPolynesia,
    label: 'French Polynesia',
    mapFile: 'frenchPolynesiaHigh.svg',
  },
  { value: JURISDICTION_IDS.gabon, label: 'Gabon', mapFile: 'gabonHigh.svg' },
  { value: JURISDICTION_IDS.gambia, label: 'Gambia', mapFile: 'gambiaHigh.svg' },
  { value: JURISDICTION_IDS.georgia, label: 'Georgia', mapFile: 'georgiaHigh.svg' },
  {
    value: JURISDICTION_IDS.georgiaWithSouthOssetia,
    label: 'Georgia (with South Ossetia)',
    mapFile: 'georgiaWithSouthOssetiaHigh.svg',
  },
  { value: JURISDICTION_IDS.germany, label: 'Germany', mapFile: 'germanyHigh.svg' },
  { value: JURISDICTION_IDS.ghana, label: 'Ghana', mapFile: 'ghanaHigh.svg' },
  { value: JURISDICTION_IDS.gibraltar, label: 'Gibraltar', mapFile: 'gibraltarHigh.svg' },
  { value: JURISDICTION_IDS.greece, label: 'Greece', mapFile: 'greeceHigh.svg' },
  { value: JURISDICTION_IDS.greenland, label: 'Greenland', mapFile: 'greenlandHigh.svg' },
  { value: JURISDICTION_IDS.grenada, label: 'Grenada', mapFile: 'grenadaHigh.svg' },
  { value: JURISDICTION_IDS.guadeloupe, label: 'Guadeloupe', mapFile: 'guadeloupeHigh.svg' },
  { value: JURISDICTION_IDS.guam, label: 'Guam', mapFile: 'guamHigh.svg' },
  { value: JURISDICTION_IDS.guatemala, label: 'Guatemala', mapFile: 'guatemalaHigh.svg' },
  { value: JURISDICTION_IDS.guineaBissau, label: 'Guinea-Bissau', mapFile: 'guineaBissauHigh.svg' },
  { value: JURISDICTION_IDS.guinea, label: 'Guinea', mapFile: 'guineaHigh.svg' },
  { value: JURISDICTION_IDS.guyana, label: 'Guyana', mapFile: 'guyanaHigh.svg' },
  { value: JURISDICTION_IDS.haiti, label: 'Haiti', mapFile: 'haitiHigh.svg' },
  { value: JURISDICTION_IDS.honduras, label: 'Honduras', mapFile: 'hondurasHigh.svg' },
  { value: JURISDICTION_IDS.hongKong, label: 'Hong Kong', mapFile: 'hongKongHigh.svg' },
  { value: JURISDICTION_IDS.hungary, label: 'Hungary', mapFile: 'hungaryHigh.svg' },
  { value: JURISDICTION_IDS.iceland, label: 'Iceland', mapFile: 'icelandHigh.svg' },
  {
    value: JURISDICTION_IDS.india2019,
    label: 'India (2019 Borders)',
    mapFile: 'india2019High.svg',
  },
  { value: JURISDICTION_IDS.india, label: 'India', mapFile: 'indiaHigh.svg' },
  { value: JURISDICTION_IDS.indonesia, label: 'Indonesia', mapFile: 'indonesiaHigh.svg' },
  { value: JURISDICTION_IDS.iran, label: 'Iran', mapFile: 'iranHigh.svg' },
  { value: JURISDICTION_IDS.iraq, label: 'Iraq', mapFile: 'iraqHigh.svg' },
  { value: JURISDICTION_IDS.ireland, label: 'Ireland', mapFile: 'irelandHigh.svg' },
  { value: JURISDICTION_IDS.isleOfMan, label: 'Isle of Man', mapFile: 'isleOfManHigh.svg' },
  { value: JURISDICTION_IDS.israel, label: 'Israel', mapFile: 'israelHigh.svg' },
  {
    value: JURISDICTION_IDS.israelPalestine,
    label: 'Israel & Palestine',
    mapFile: 'israelPalestineHigh.svg',
  },
  { value: JURISDICTION_IDS.italy, label: 'Italy', mapFile: 'italyHigh.svg' },
  { value: JURISDICTION_IDS.ivoryCoast, label: 'Ivory Coast', mapFile: 'ivoryCoastHigh.svg' },
  { value: JURISDICTION_IDS.jamaica, label: 'Jamaica', mapFile: 'jamaicaHigh.svg' },
  { value: JURISDICTION_IDS.japan, label: 'Japan', mapFile: 'japanHigh.svg' },
  { value: JURISDICTION_IDS.jersey, label: 'Jersey', mapFile: 'jerseyHigh.svg' },
  { value: JURISDICTION_IDS.jordan, label: 'Jordan', mapFile: 'jordanHigh.svg' },
  { value: JURISDICTION_IDS.kazakhstan, label: 'Kazakhstan', mapFile: 'kazakhstanHigh.svg' },
  { value: JURISDICTION_IDS.kenya, label: 'Kenya', mapFile: 'kenyaHigh.svg' },
  { value: JURISDICTION_IDS.kiribati, label: 'Kiribati', mapFile: 'kiribatiHigh.svg' },
  { value: JURISDICTION_IDS.kosovo, label: 'Kosovo', mapFile: 'kosovoHigh.svg' },
  { value: JURISDICTION_IDS.kuwait, label: 'Kuwait', mapFile: 'kuwaitHigh.svg' },
  { value: JURISDICTION_IDS.kyrgyzstan, label: 'Kyrgyzstan', mapFile: 'kyrgyzstanHigh.svg' },
  { value: JURISDICTION_IDS.laos, label: 'Laos', mapFile: 'laosHigh.svg' },
  { value: JURISDICTION_IDS.latinAmerica, label: 'Latin America', mapFile: 'latinAmericaHigh.svg' },
  { value: JURISDICTION_IDS.latvia, label: 'Latvia', mapFile: 'latviaHigh.svg' },
  { value: JURISDICTION_IDS.lebanon, label: 'Lebanon', mapFile: 'lebanonHigh.svg' },
  { value: JURISDICTION_IDS.lesotho, label: 'Lesotho', mapFile: 'lesothoHigh.svg' },
  { value: JURISDICTION_IDS.liberia, label: 'Liberia', mapFile: 'liberiaHigh.svg' },
  { value: JURISDICTION_IDS.libya, label: 'Libya', mapFile: 'libyaHigh.svg' },
  {
    value: JURISDICTION_IDS.liechtenstein,
    label: 'Liechtenstein',
    mapFile: 'liechtensteinHigh.svg',
  },
  { value: JURISDICTION_IDS.lithuania, label: 'Lithuania', mapFile: 'lithuaniaHigh.svg' },
  { value: JURISDICTION_IDS.luxembourg, label: 'Luxembourg', mapFile: 'luxembourgHigh.svg' },
  { value: JURISDICTION_IDS.macao, label: 'Macao', mapFile: 'macaoHigh.svg' },
  { value: JURISDICTION_IDS.madagascar, label: 'Madagascar', mapFile: 'madagascarHigh.svg' },
  { value: JURISDICTION_IDS.malawi, label: 'Malawi', mapFile: 'malawiHigh.svg' },
  { value: JURISDICTION_IDS.malaysia, label: 'Malaysia', mapFile: 'malaysiaHigh.svg' },
  { value: JURISDICTION_IDS.maldives, label: 'Maldives', mapFile: 'maldivesHigh.svg' },
  { value: JURISDICTION_IDS.mali, label: 'Mali', mapFile: 'maliHigh.svg' },
  { value: JURISDICTION_IDS.malta, label: 'Malta', mapFile: 'maltaHigh.svg' },
  {
    value: JURISDICTION_IDS.marshallIslands,
    label: 'Marshall Islands',
    mapFile: 'marshallIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.martinique, label: 'Martinique', mapFile: 'martiniqueHigh.svg' },
  { value: JURISDICTION_IDS.mauritania, label: 'Mauritania', mapFile: 'mauritaniaHigh.svg' },
  { value: JURISDICTION_IDS.mauritius, label: 'Mauritius', mapFile: 'mauritiusHigh.svg' },
  { value: JURISDICTION_IDS.mayotte, label: 'Mayotte', mapFile: 'mayotteHigh.svg' },
  { value: JURISDICTION_IDS.mexico, label: 'Mexico', mapFile: 'mexicoHigh.svg' },
  { value: JURISDICTION_IDS.micronesia, label: 'Micronesia', mapFile: 'micronesiaHigh.svg' },
  { value: JURISDICTION_IDS.middleEast, label: 'Middle East', mapFile: 'middleEastHigh.svg' },
  { value: JURISDICTION_IDS.moldova, label: 'Moldova', mapFile: 'moldovaHigh.svg' },
  { value: JURISDICTION_IDS.monaco, label: 'Monaco', mapFile: 'monacoHigh.svg' },
  { value: JURISDICTION_IDS.mongolia, label: 'Mongolia', mapFile: 'mongoliaHigh.svg' },
  { value: JURISDICTION_IDS.montenegro, label: 'Montenegro', mapFile: 'montenegroHigh.svg' },
  { value: JURISDICTION_IDS.montserrat, label: 'Montserrat', mapFile: 'montserratHigh.svg' },
  {
    value: JURISDICTION_IDS.morocco2015,
    label: 'Morocco (2015 Regions)',
    mapFile: 'morocco2015High.svg',
  },
  { value: JURISDICTION_IDS.morocco, label: 'Morocco', mapFile: 'moroccoHigh.svg' },
  {
    value: JURISDICTION_IDS.moroccoWesternSahara,
    label: 'Morocco & Western Sahara',
    mapFile: 'moroccoWesternSaharaHigh.svg',
  },
  { value: JURISDICTION_IDS.mozambique, label: 'Mozambique', mapFile: 'mozambiqueHigh.svg' },
  { value: JURISDICTION_IDS.myanmar, label: 'Myanmar', mapFile: 'myanmarHigh.svg' },
  { value: JURISDICTION_IDS.namibia, label: 'Namibia', mapFile: 'namibiaHigh.svg' },
  { value: JURISDICTION_IDS.nauru, label: 'Nauru', mapFile: 'nauruHigh.svg' },
  { value: JURISDICTION_IDS.nepal, label: 'Nepal', mapFile: 'nepalHigh.svg' },
  { value: JURISDICTION_IDS.netherlands, label: 'Netherlands', mapFile: 'netherlandsHigh.svg' },
  { value: JURISDICTION_IDS.newCaledonia, label: 'New Caledonia', mapFile: 'newCaledoniaHigh.svg' },
  { value: JURISDICTION_IDS.newZealand, label: 'New Zealand', mapFile: 'newZealandHigh.svg' },
  { value: JURISDICTION_IDS.nicaragua, label: 'Nicaragua', mapFile: 'nicaraguaHigh.svg' },
  { value: JURISDICTION_IDS.niger, label: 'Niger', mapFile: 'nigerHigh.svg' },
  { value: JURISDICTION_IDS.nigeria, label: 'Nigeria', mapFile: 'nigeriaHigh.svg' },
  { value: JURISDICTION_IDS.niue, label: 'Niue', mapFile: 'niueHigh.svg' },
  { value: JURISDICTION_IDS.northAmerica, label: 'North America', mapFile: 'northAmericaHigh.svg' },
  {
    value: JURISDICTION_IDS.northAmericaNoGreenland,
    label: 'North America (No Greenland)',
    mapFile: 'northAmericaNoGreenlandHigh.svg',
  },
  {
    value: JURISDICTION_IDS.northernMarianaIslands,
    label: 'Northern Mariana Islands',
    mapFile: 'northernMarianaIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.northKorea, label: 'North Korea', mapFile: 'northKoreaHigh.svg' },
  {
    value: JURISDICTION_IDS.northMacedonia,
    label: 'North Macedonia',
    mapFile: 'northMacedoniaHigh.svg',
  },
  { value: JURISDICTION_IDS.norway, label: 'Norway', mapFile: 'norwayHigh.svg' },
  { value: JURISDICTION_IDS.oman, label: 'Oman', mapFile: 'omanHigh.svg' },
  { value: JURISDICTION_IDS.pakistan, label: 'Pakistan', mapFile: 'pakistanHigh.svg' },
  { value: JURISDICTION_IDS.palau, label: 'Palau', mapFile: 'palauHigh.svg' },
  { value: JURISDICTION_IDS.palestine, label: 'Palestine', mapFile: 'palestineHigh.svg' },
  { value: JURISDICTION_IDS.panama, label: 'Panama', mapFile: 'panamaHigh.svg' },
  {
    value: JURISDICTION_IDS.papuaNewGuinea,
    label: 'Papua New Guinea',
    mapFile: 'papuaNewGuineaHigh.svg',
  },
  { value: JURISDICTION_IDS.paraguay, label: 'Paraguay', mapFile: 'paraguayHigh.svg' },
  { value: JURISDICTION_IDS.peru, label: 'Peru', mapFile: 'peruHigh.svg' },
  { value: JURISDICTION_IDS.philippines, label: 'Philippines', mapFile: 'philippinesHigh.svg' },
  {
    value: JURISDICTION_IDS.pitcairnIslands,
    label: 'Pitcairn Islands',
    mapFile: 'pitcairnIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.poland, label: 'Poland', mapFile: 'polandHigh.svg' },
  { value: JURISDICTION_IDS.portugal, label: 'Portugal', mapFile: 'portugalHigh.svg' },
  {
    value: JURISDICTION_IDS.portugalRegions,
    label: 'Portugal (Regions)',
    mapFile: 'portugalRegionsHigh.svg',
  },
  { value: JURISDICTION_IDS.puertoRico, label: 'Puerto Rico', mapFile: 'puertoRicoHigh.svg' },
  { value: JURISDICTION_IDS.qatar, label: 'Qatar', mapFile: 'qatarHigh.svg' },
  { value: JURISDICTION_IDS.reunion, label: 'Réunion', mapFile: 'reunionHigh.svg' },
  { value: JURISDICTION_IDS.romania, label: 'Romania', mapFile: 'romaniaHigh.svg' },
  { value: JURISDICTION_IDS.russia, label: 'Russia', mapFile: 'russiaHigh.svg' },
  { value: JURISDICTION_IDS.rwanda, label: 'Rwanda', mapFile: 'rwandaHigh.svg' },
  { value: JURISDICTION_IDS.saintMartin, label: 'Saint Martin', mapFile: 'saintMartinHigh.svg' },
  { value: JURISDICTION_IDS.samoa, label: 'Samoa', mapFile: 'samoaHigh.svg' },
  { value: JURISDICTION_IDS.sanMarino, label: 'San Marino', mapFile: 'sanMarinoHigh.svg' },
  {
    value: JURISDICTION_IDS.saoTomeAndPrincipe,
    label: 'São Tomé and Príncipe',
    mapFile: 'saoTomeAndPrincipeHigh.svg',
  },
  { value: JURISDICTION_IDS.saudiArabia, label: 'Saudi Arabia', mapFile: 'saudiArabiaHigh.svg' },
  { value: JURISDICTION_IDS.senegal, label: 'Senegal', mapFile: 'senegalHigh.svg' },
  { value: JURISDICTION_IDS.serbia, label: 'Serbia', mapFile: 'serbiaHigh.svg' },
  {
    value: JURISDICTION_IDS.serbiaNoKosovo,
    label: 'Serbia (No Kosovo)',
    mapFile: 'serbiaNoKosovoHigh.svg',
  },
  { value: JURISDICTION_IDS.seychelles, label: 'Seychelles', mapFile: 'seychellesHigh.svg' },
  { value: JURISDICTION_IDS.sierraLeone, label: 'Sierra Leone', mapFile: 'sierraLeoneHigh.svg' },
  { value: JURISDICTION_IDS.singapore, label: 'Singapore', mapFile: 'singaporeHigh.svg' },
  { value: JURISDICTION_IDS.sintMaarten, label: 'Sint Maarten', mapFile: 'sintMaartenHigh.svg' },
  { value: JURISDICTION_IDS.slovakia, label: 'Slovakia', mapFile: 'slovakiaHigh.svg' },
  { value: JURISDICTION_IDS.slovenia, label: 'Slovenia', mapFile: 'sloveniaHigh.svg' },
  {
    value: JURISDICTION_IDS.solomonIslands,
    label: 'Solomon Islands',
    mapFile: 'solomonIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.somalia, label: 'Somalia', mapFile: 'somaliaHigh.svg' },
  { value: JURISDICTION_IDS.southAfrica, label: 'South Africa', mapFile: 'southAfricaHigh.svg' },
  { value: JURISDICTION_IDS.southAmerica, label: 'South America', mapFile: 'southAmericaHigh.svg' },
  { value: JURISDICTION_IDS.southKorea, label: 'South Korea', mapFile: 'southKoreaHigh.svg' },
  { value: JURISDICTION_IDS.southSudan, label: 'South Sudan', mapFile: 'southSudanHigh.svg' },
  { value: JURISDICTION_IDS.spain, label: 'Spain', mapFile: 'spainHigh.svg' },
  {
    value: JURISDICTION_IDS.spainProvinces,
    label: 'Spain (Provinces)',
    mapFile: 'spainProvincesHigh.svg',
  },
  { value: JURISDICTION_IDS.sriLanka, label: 'Sri Lanka', mapFile: 'sriLankaHigh.svg' },
  { value: JURISDICTION_IDS.stHelena, label: 'St. Helena', mapFile: 'stHelenaHigh.svg' },
  {
    value: JURISDICTION_IDS.stKittsAndNevis,
    label: 'St. Kitts and Nevis',
    mapFile: 'stKittsAndNevisHigh.svg',
  },
  { value: JURISDICTION_IDS.stLucia, label: 'St. Lucia', mapFile: 'stLuciaHigh.svg' },
  { value: JURISDICTION_IDS.sudan, label: 'Sudan', mapFile: 'sudanHigh.svg' },
  { value: JURISDICTION_IDS.suriname, label: 'Suriname', mapFile: 'surinameHigh.svg' },
  {
    value: JURISDICTION_IDS.svalbardAndJanMayen,
    label: 'Svalbard and Jan Mayen',
    mapFile: 'svalbardAndJanMayenHigh.svg',
  },
  { value: JURISDICTION_IDS.sweden, label: 'Sweden', mapFile: 'swedenHigh.svg' },
  { value: JURISDICTION_IDS.switzerland, label: 'Switzerland', mapFile: 'switzerlandHigh.svg' },
  { value: JURISDICTION_IDS.syria, label: 'Syria', mapFile: 'syriaHigh.svg' },
  { value: JURISDICTION_IDS.taiwan, label: 'Taiwan', mapFile: 'taiwanHigh.svg' },
  { value: JURISDICTION_IDS.tajikistan, label: 'Tajikistan', mapFile: 'tajikistanHigh.svg' },
  { value: JURISDICTION_IDS.tanzania, label: 'Tanzania', mapFile: 'tanzaniaHigh.svg' },
  { value: JURISDICTION_IDS.thailand, label: 'Thailand', mapFile: 'thailandHigh.svg' },
  { value: JURISDICTION_IDS.tibet, label: 'Tibet', mapFile: 'tibetHigh.svg' },
  { value: JURISDICTION_IDS.togo, label: 'Togo', mapFile: 'togoHigh.svg' },
  { value: JURISDICTION_IDS.tokelau, label: 'Tokelau', mapFile: 'tokelauHigh.svg' },
  { value: JURISDICTION_IDS.tonga, label: 'Tonga', mapFile: 'tongaHigh.svg' },
  {
    value: JURISDICTION_IDS.trinidadAndTobago,
    label: 'Trinidad and Tobago',
    mapFile: 'trinidadAndTobagoHigh.svg',
  },
  { value: JURISDICTION_IDS.tunisia, label: 'Tunisia', mapFile: 'tunisiaHigh.svg' },
  { value: JURISDICTION_IDS.turkey, label: 'Turkey', mapFile: 'turkeyHigh.svg' },
  { value: JURISDICTION_IDS.turkmenistan, label: 'Turkmenistan', mapFile: 'turkmenistanHigh.svg' },
  {
    value: JURISDICTION_IDS.turksAndCaicosIslands,
    label: 'Turks and Caicos Islands',
    mapFile: 'turksAndCaicosIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.tuvalu, label: 'Tuvalu', mapFile: 'tuvaluHigh.svg' },
  { value: JURISDICTION_IDS.uganda, label: 'Uganda', mapFile: 'ugandaHigh.svg' },
  { value: JURISDICTION_IDS.ukraine, label: 'Ukraine', mapFile: 'ukraineHigh.svg' },
  {
    value: JURISDICTION_IDS.unitedArabEmirates,
    label: 'United Arab Emirates',
    mapFile: 'unitedArabEmiratesHigh.svg',
  },
  {
    value: JURISDICTION_IDS.unitedKingdom,
    label: 'United Kingdom',
    mapFile: 'unitedKingdomHigh.svg',
  },
  { value: JURISDICTION_IDS.unRegions, label: 'UN Regions', mapFile: 'unRegionsHigh.svg' },
  { value: JURISDICTION_IDS.uruguay, label: 'Uruguay', mapFile: 'uruguayHigh.svg' },
  { value: JURISDICTION_IDS.usa, label: 'United States', mapFile: 'usaHigh.svg' },
  {
    value: JURISDICTION_IDS.usaMercator,
    label: 'United States (Mercator)',
    mapFile: 'usaMercatorHigh.svg',
  },
  {
    value: JURISDICTION_IDS.usaTerritoriesAssociatedStates,
    label: 'USA Territories & Associated States',
    mapFile: 'usaTerritoriesAssociatedStatesHigh.svg',
  },
  {
    value: JURISDICTION_IDS.usaTerritories,
    label: 'USA Territories',
    mapFile: 'usaTerritoriesHigh.svg',
  },
  {
    value: JURISDICTION_IDS.usVirginIslands,
    label: 'US Virgin Islands',
    mapFile: 'usVirginIslandsHigh.svg',
  },
  { value: JURISDICTION_IDS.uzbekistan, label: 'Uzbekistan', mapFile: 'uzbekistanHigh.svg' },
  { value: JURISDICTION_IDS.vanuatu, label: 'Vanuatu', mapFile: 'vanuatuHigh.svg' },
  { value: JURISDICTION_IDS.venezuela, label: 'Venezuela', mapFile: 'venezuelaHigh.svg' },
  { value: JURISDICTION_IDS.vietnam, label: 'Vietnam', mapFile: 'vietnamHigh.svg' },
  {
    value: JURISDICTION_IDS.wallisAndFutuna,
    label: 'Wallis and Futuna',
    mapFile: 'wallisAndFutunaHigh.svg',
  },
  {
    value: JURISDICTION_IDS.worldAntarctica,
    label: 'World (with Antarctica)',
    mapFile: 'worldAntarcticaHigh.svg',
  },
  { value: JURISDICTION_IDS.world, label: 'World', mapFile: 'worldHigh.svg' },
  {
    value: JURISDICTION_IDS.worldIndia,
    label: 'World (India View)',
    mapFile: 'worldIndiaHigh.svg',
  },
  {
    value: JURISDICTION_IDS.worldPacificRim,
    label: 'World (Pacific Rim)',
    mapFile: 'worldPacificRimHigh.svg',
  },
  {
    value: JURISDICTION_IDS.worldRussiaSplit,
    label: 'World (Russia Split)',
    mapFile: 'worldRussiaSplitHigh.svg',
  },
  { value: JURISDICTION_IDS.yemen, label: 'Yemen', mapFile: 'yemenHigh.svg' },
  { value: JURISDICTION_IDS.zambia, label: 'Zambia', mapFile: 'zambiaHigh.svg' },
  { value: JURISDICTION_IDS.zimbabwe, label: 'Zimbabwe', mapFile: 'zimbabweHigh.svg' },
];
