import type { CountryRow } from '@/data/parseCountries';

export type MarketingCountry = Pick<CountryRow, 'slug'> & { name: CountryRow['name_en'] };

export const MARKETING_COUNTRIES: MarketingCountry[] = [
  // { slug: 'afghanistan', name: 'Afghanistan' },
  // { slug: 'albania', name: 'Albania' },
  // { slug: 'algeria', name: 'Algeria' },
  // { slug: 'americanSamoa', name: 'American Samoa' },
  // { slug: 'andorra', name: 'Andorra' },
  // { slug: 'angola', name: 'Angola' },
  // { slug: 'anguilla', name: 'Anguilla' },
  // { slug: 'antiguaAndBarbuda', name: 'Antigua and Barbuda' },
  // { slug: 'argentina', name: 'Argentina' },
  // { slug: 'armenia', name: 'Armenia' },
  // { slug: 'aruba', name: 'Aruba' },
  // { slug: 'australia', name: 'Australia' },
  // { slug: 'austria', name: 'Austria' },
  // { slug: 'bahamas', name: 'Bahamas' },
  // { slug: 'bahrain', name: 'Bahrain' },
  // { slug: 'bangladesh', name: 'Bangladesh' },
  // { slug: 'barbados', name: 'Barbados' },
  // { slug: 'belarus', name: 'Belarus' },
  // { slug: 'belgium', name: 'Belgium' },
  // { slug: 'belize', name: 'Belize' },
  // { slug: 'benin', name: 'Benin' },
  // { slug: 'bermuda', name: 'Bermuda' },
  // { slug: 'bhutan', name: 'Bhutan' },
  // { slug: 'bolivia', name: 'Bolivia' },
  // { slug: 'botswana', name: 'Botswana' },
  // { slug: 'brazil', name: 'Brazil' },
  // { slug: 'britishVirginIslands', name: 'British Virgin Islands' },
  // { slug: 'bruneiDarussalam', name: 'Brunei' },
  // { slug: 'bulgaria', name: 'Bulgaria' },
  // { slug: 'burkinaFaso', name: 'Burkina Faso' },
  { slug: 'burundi', name: 'Burundi' },
  { slug: 'cambodia', name: 'Cambodia' },
  { slug: 'cameroon', name: 'Cameroon' },
  { slug: 'canada', name: 'Canada' },
  { slug: 'capeVerde', name: 'Cape Verde' },
  { slug: 'caribbeanNetherlands', name: 'Caribbean Netherlands' },
  { slug: 'caymanIslands', name: 'Cayman Islands' },
  { slug: 'centralAfricanRepublic', name: 'Central African Republic' },
  { slug: 'chad', name: 'Chad' },
  { slug: 'channelIslands', name: 'Channel Islands' },
  // { slug: 'chile', name: 'Chile' },
  // { slug: 'china', name: 'China' },
  // { slug: 'christmasIsland', name: 'Christmas Island' },
  // { slug: 'cocosIslands', name: 'Cocos Islands' },
  // { slug: 'colombia', name: 'Colombia' },
  // { slug: 'comoros', name: 'Comoros' },
  // { slug: 'congo', name: 'Republic of the Congo' },
  // { slug: 'congoDR', name: 'DR Congo' },
  // { slug: 'cookIslands', name: 'Cook Islands' },
  // { slug: 'costaRica', name: 'Costa Rica' },
  // { slug: 'croatia', name: 'Croatia' },
  // { slug: 'cuba', name: 'Cuba' },
  // { slug: 'curacao', name: 'Curaçao' },
  // { slug: 'cyprus', name: 'Cyprus' },
  // { slug: 'czechRepublic', name: 'Czech Republic' },
  // { slug: 'denmark', name: 'Denmark' },
  // { slug: 'djibouti', name: 'Djibouti' },
  // { slug: 'dominica', name: 'Dominica' },
  // { slug: 'dominicanRepublic', name: 'Dominican Republic' },
  // { slug: 'eastTimor', name: 'East Timor' },
  // { slug: 'ecuador', name: 'Ecuador' },
  // { slug: 'egypt', name: 'Egypt' },
  // { slug: 'elSalvador', name: 'El Salvador' },
  // { slug: 'equatorialGuinea', name: 'Equatorial Guinea' },
  // { slug: 'eritrea', name: 'Eritrea' },
  // { slug: 'estonia', name: 'Estonia' },
  // { slug: 'eSwatini', name: 'Eswatini' },
  // { slug: 'ethiopia', name: 'Ethiopia' },
  // { slug: 'falklandIslands', name: 'Falkland Islands' },
  // { slug: 'faroeIslands', name: 'Faroe Islands' },
  // { slug: 'fijiEast', name: 'Fiji' },
  // { slug: 'finland', name: 'Finland' },
  // { slug: 'france', name: 'France' },
  // { slug: 'frenchGuiana', name: 'French Guiana' },
  // { slug: 'frenchPolynesia', name: 'French Polynesia' },
  // { slug: 'gabon', name: 'Gabon' },
  // { slug: 'gambia', name: 'Gambia' },
  // { slug: 'georgia', name: 'Georgia' },
  // { slug: 'germany', name: 'Germany' },
  // { slug: 'ghana', name: 'Ghana' },
  // { slug: 'gibraltar', name: 'Gibraltar' },
  // { slug: 'greece', name: 'Greece' },
  // { slug: 'greenland', name: 'Greenland' },
  // { slug: 'grenada', name: 'Grenada' },
  // { slug: 'guadeloupe', name: 'Guadeloupe' },
  // { slug: 'guam', name: 'Guam' },
  // { slug: 'guatemala', name: 'Guatemala' },
  // { slug: 'guinea', name: 'Guinea' },
  // { slug: 'guineaBissau', name: 'Guinea-Bissau' },
  // { slug: 'guyana', name: 'Guyana' },
  // { slug: 'haiti', name: 'Haiti' },
  // { slug: 'honduras', name: 'Honduras' },
  // { slug: 'hongKong', name: 'Hong Kong' },
  // { slug: 'hungary', name: 'Hungary' },
  // { slug: 'iceland', name: 'Iceland' },
  // { slug: 'india', name: 'India' },
  // { slug: 'indonesia', name: 'Indonesia' },
  // { slug: 'iran', name: 'Iran' },
  // { slug: 'iraq', name: 'Iraq' },
  // { slug: 'ireland', name: 'Ireland' },
  // { slug: 'isleOfMan', name: 'Isle of Man' },
  // { slug: 'israel', name: 'Israel' },
  // { slug: 'italy', name: 'Italy' },
  // { slug: 'ivoryCoast', name: 'Ivory Coast' },
  // { slug: 'jamaica', name: 'Jamaica' },
  // { slug: 'japan', name: 'Japan' },
  // { slug: 'jersey', name: 'Jersey' },
  // { slug: 'jordan', name: 'Jordan' },
  // { slug: 'kazakhstan', name: 'Kazakhstan' },
  // { slug: 'kenya', name: 'Kenya' },
  // { slug: 'kiribati', name: 'Kiribati' },
  // { slug: 'kosovo', name: 'Kosovo' },
  // { slug: 'kuwait', name: 'Kuwait' },
  // { slug: 'kyrgyzstan', name: 'Kyrgyzstan' },
  // { slug: 'laos', name: 'Laos' },
  // { slug: 'latvia', name: 'Latvia' },
  // { slug: 'lebanon', name: 'Lebanon' },
  // { slug: 'lesotho', name: 'Lesotho' },
  // { slug: 'liberia', name: 'Liberia' },
  // { slug: 'libya', name: 'Libya' },
  // { slug: 'liechtenstein', name: 'Liechtenstein' },
  // { slug: 'lithuania', name: 'Lithuania' },
  // { slug: 'luxembourg', name: 'Luxembourg' },
  // { slug: 'macao', name: 'Macao' },
  // { slug: 'madagascar', name: 'Madagascar' },
  // { slug: 'malawi', name: 'Malawi' },
  // { slug: 'malaysia', name: 'Malaysia' },
  // { slug: 'maldives', name: 'Maldives' },
  // { slug: 'mali', name: 'Mali' },
  // { slug: 'malta', name: 'Malta' },
  // { slug: 'marshallIslands', name: 'Marshall Islands' },
  // { slug: 'martinique', name: 'Martinique' },
  // { slug: 'mauritania', name: 'Mauritania' },
  // { slug: 'mauritius', name: 'Mauritius' },
  // { slug: 'mayotte', name: 'Mayotte' },
  // { slug: 'mexico', name: 'Mexico' },
  // { slug: 'micronesia', name: 'Micronesia' },
  // { slug: 'moldova', name: 'Moldova' },
  // { slug: 'monaco', name: 'Monaco' },
  // { slug: 'mongolia', name: 'Mongolia' },
  // { slug: 'montenegro', name: 'Montenegro' },
  // { slug: 'montserrat', name: 'Montserrat' },
  // { slug: 'morocco', name: 'Morocco' },
  // { slug: 'mozambique', name: 'Mozambique' },
  // { slug: 'myanmar', name: 'Myanmar' },
  // { slug: 'namibia', name: 'Namibia' },
  // { slug: 'nauru', name: 'Nauru' },
  // { slug: 'nepal', name: 'Nepal' },
  // { slug: 'netherlands', name: 'Netherlands' },
  // { slug: 'newCaledonia', name: 'New Caledonia' },
  // { slug: 'newZealand', name: 'New Zealand' },
  // { slug: 'nicaragua', name: 'Nicaragua' },
  // { slug: 'niger', name: 'Niger' },
  // { slug: 'nigeria', name: 'Nigeria' },
  // { slug: 'niue', name: 'Niue' },
  // { slug: 'northernMarianaIslands', name: 'Northern Mariana Islands' },
  // { slug: 'northKorea', name: 'North Korea' },
  // { slug: 'northMacedonia', name: 'North Macedonia' },
  // { slug: 'norway', name: 'Norway' },
  // { slug: 'oman', name: 'Oman' },
  // { slug: 'pakistan', name: 'Pakistan' },
  // { slug: 'palau', name: 'Palau' },
  // { slug: 'palestine', name: 'Palestine' },
  // { slug: 'panama', name: 'Panama' },
  // { slug: 'papuaNewGuinea', name: 'Papua New Guinea' },
  // { slug: 'paraguay', name: 'Paraguay' },
  // { slug: 'peru', name: 'Peru' },
  // { slug: 'philippines', name: 'Philippines' },
  // { slug: 'pitcairnIslands', name: 'Pitcairn Islands' },
  // { slug: 'poland', name: 'Poland' },
  // { slug: 'portugal', name: 'Portugal' },
  // { slug: 'puertoRico', name: 'Puerto Rico' },
  // { slug: 'qatar', name: 'Qatar' },
  // { slug: 'reunion', name: 'Réunion' },
  // { slug: 'romania', name: 'Romania' },
  // { slug: 'russia', name: 'Russia' },
  // { slug: 'rwanda', name: 'Rwanda' },
  // { slug: 'saintMartin', name: 'Saint Martin' },
  // { slug: 'samoa', name: 'Samoa' },
  // { slug: 'sanMarino', name: 'San Marino' },
  // { slug: 'saoTomeAndPrincipe', name: 'São Tomé and Príncipe' },
  // { slug: 'saudiArabia', name: 'Saudi Arabia' },
  // { slug: 'senegal', name: 'Senegal' },
  // { slug: 'serbia', name: 'Serbia' },
  // { slug: 'seychelles', name: 'Seychelles' },
  // { slug: 'sierraLeone', name: 'Sierra Leone' },
  // { slug: 'singapore', name: 'Singapore' },
  // { slug: 'sintMaarten', name: 'Sint Maarten' },
  // { slug: 'slovakia', name: 'Slovakia' },
  // { slug: 'slovenia', name: 'Slovenia' },
  // { slug: 'solomonIslands', name: 'Solomon Islands' },
  // { slug: 'somalia', name: 'Somalia' },
  // { slug: 'southAfrica', name: 'South Africa' },
  // { slug: 'southKorea', name: 'South Korea' },
  // { slug: 'southSudan', name: 'South Sudan' },
  // { slug: 'spain', name: 'Spain' },
  // { slug: 'sriLanka', name: 'Sri Lanka' },
  // { slug: 'stHelena', name: 'Saint Helena' },
  // { slug: 'stKittsAndNevis', name: 'Saint Kitts and Nevis' },
  // { slug: 'stLucia', name: 'Saint Lucia' },
  // { slug: 'sudan', name: 'Sudan' },
  // { slug: 'suriname', name: 'Suriname' },
  // { slug: 'svalbardAndJanMayen', name: 'Svalbard and Jan Mayen' },
  // { slug: 'sweden', name: 'Sweden' },
  // { slug: 'switzerland', name: 'Switzerland' },
  // { slug: 'syria', name: 'Syria' },
  // { slug: 'taiwan', name: 'Taiwan' },
  // { slug: 'tajikistan', name: 'Tajikistan' },
  // { slug: 'tanzania', name: 'Tanzania' },
  // { slug: 'thailand', name: 'Thailand' },
  // { slug: 'tibet', name: 'Tibet' },
  // { slug: 'togo', name: 'Togo' },
  // { slug: 'tokelau', name: 'Tokelau' },
  // { slug: 'tonga', name: 'Tonga' },
  // { slug: 'trinidadAndTobago', name: 'Trinidad and Tobago' },
  // { slug: 'tunisia', name: 'Tunisia' },
  // { slug: 'turkmenistan', name: 'Turkmenistan' },
  // { slug: 'turksAndCaicosIslands', name: 'Turks and Caicos Islands' },
  // { slug: 'tuvalu', name: 'Tuvalu' },
  // { slug: 'uganda', name: 'Uganda' },
  // { slug: 'ukraine', name: 'Ukraine' },
  // { slug: 'unitedArabEmirates', name: 'United Arab Emirates' },
  // { slug: 'unitedKingdom', name: 'United Kingdom' },
  // { slug: 'uruguay', name: 'Uruguay' },
  // { slug: 'usa', name: 'United States' },
  // { slug: 'usVirginIslands', name: 'U.S. Virgin Islands' },
  // { slug: 'uzbekistan', name: 'Uzbekistan' },
  // { slug: 'vanuatu', name: 'Vanuatu' },
  // { slug: 'venezuela', name: 'Venezuela' },
  // { slug: 'vietnam', name: 'Vietnam' },
  // { slug: 'wallisAndFutuna', name: 'Wallis and Futuna' },
  // { slug: 'yemen', name: 'Yemen' },
  // { slug: 'zambia', name: 'Zambia' },
  // { slug: 'zimbabwe', name: 'Zimbabwe' },
];

// Countries marketing assets are already generated for:
// armenia
// brazil
// germany
// india
// russia
